# Generated by Django 5.0.7 on 2024-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usermodel_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
