# Generated by Django 5.0.7 on 2024-07-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_orderitems_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirm', models.BooleanField(default=True)),
                ('date_confirm', models.DateField()),
                ('cart_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitems')),
            ],
        ),
    ]
