# Generated by Django 5.0.7 on 2024-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
